[project]
name = "sps-genai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "yj", email = "ys4017@columbia.edu" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.141.1",
    "jupyter>=1.1.1",
    "pydantic>=2.13.5",
    "uvicorn>=0.53.0",
]

[project.scripts]
sps-genai = "sps_genai:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
