[project]
name = "sps-genai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "yj", email = "ys4017@columbia.edu" }
]
requires-python = ">=3.13"
dependencies = [
    "en-core-web-lg",
    "fastapi[standard]>=0.141.1",
    "jupyter>=1.1.1",
    "pydantic>=2.13.5",
    "spacy>=3.8.16",
    "uvicorn>=0.53.0",
]

[tool.uv.sources]
en-core-web-lg = { url = "https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-3.8.0/en_core_web_lg-3.8.0-py3-none-any.whl" }
